# This file is part of the CampaignChain package.
#
# (c) Sandro Groganz <sandro@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    campaignchain_security_authentication_client_oauth:
        debug_mode: false
        debug_file: /Users/ordnas/campaignchain/app/logs/oauth.log

services:
#    campaignchain_security_authentication_client_o_auth.example:
#        class: %campaignchain_security_authentication_client_o_auth.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    campaignchain.security.authentication.client.oauth.authentication:
        class: CampaignChain\Security\Authentication\Client\OAuthBundle\Authentication
        calls:
            - [setContainer, ["@service_container"]]
    campaignchain.security.authentication.client.oauth.application:
        class: CampaignChain\Security\Authentication\Client\OAuthBundle\EntityService\ApplicationService
        arguments: [ @doctrine.orm.entity_manager, @service_container ]
    campaignchain.security.authentication.client.oauth.token:
        class: CampaignChain\Security\Authentication\Client\OAuthBundle\EntityService\TokenService
        arguments: [ @doctrine.orm.entity_manager, @service_container ]